name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Spring Boot backend
        run: |
          cd weather-app
          mvn clean package

      - name: Build Docker image for backend
        run: |
          docker build -t weather-backend:ci ./weather-app
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      -  name: Build Docker image
         run: |
         docker build -t ${{ secrets.DOCKER_USERNAME }}/weather-backend:latest ./weather-app

      -   name: Push Docker image
          run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/weather-backend:latest


